name: Publish Docker Image

on:
  push:
    branches: 
      - 'main'
      - 'test'

jobs:

  build:
    env:
      BUILD_VERSION: 'v0.0'
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3    
    - name: Create Next Tag
      id: get_tag_name
      run: | 
        git fetch --prune --prune-tags
        echo $BUILD_ID
        echo $(bash ./.github/workflows/tag.bash)
        echo "BUILD_ID=${BUILD_VERSION}-$(bash ./.github/workflows/tag.bash)" >> $GITHUB_ENV
        echo "BUILD_ID=${BUILD_VERSION}-$(bash ./.github/workflows/tag.bash)" >> $GITHUB_OUTPUT

    - name: Tag
      run: |
        tag=$BUILD_ID
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git tag -a "${tag}" -m "new tag"
        git push origin "${tag}"

    - name: Build the Docker image
      run: |
        echo '${{ secrets.JSON_GCLOUD_SERVICE_ACCOUNT_JSON }}' > credential-token.json 
        docker build -t gcr.io/mert-personal/database-api2:${BUILD_ID} .
        
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.JSON_GCLOUD_SERVICE_ACCOUNT_JSON }}'
    - name: Pushing the image
      uses: RafikFarhad/push-to-gcr-github-action@v5-rc1 # <- use this on your workflow
      with:
        registry: gcr.io
        project_id: mert-personal
        image_name: database-api2
        image_tag: ${{ steps.get_tag_name.outputs.BUILD_ID }}
        push_only: true
